version: 2

updates:
  - package-ecosystem: npm
    directory: /src/ChangeMe.Frontend
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-eslint/*"
          - "@angular/build"
          - "@angular/cli"
          - primeng
          - "@primeuix/*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /src/ChangeMe.Backend
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
