namespace ChangeMe.Backend.Domain.Aggregates.Notifications.Enums;

public enum NotificationEventType
{
  COMMENT_CREATED = 0,
  STATUS_CHANGED = 1,
  PRIORITY_CHANGED = 2,
  ASSIGNEE_CHANGED = 3,
  TITLE_CHANGED = 4,
  ISSUE_REOPENED = 5,
  ISSUE_CLOSED = 6,
  DESCRIPTION_CHANGED = 7,
  ACCEPTANCE_CRITERION_ADDED = 8,
  ACCEPTANCE_CRITERION_UPDATED = 9,
  ACCEPTANCE_CRITERION_REMOVED = 10,
  ATTACHMENT_ADDED = 11,
  ATTACHMENT_REMOVED = 12,
  AVAILABILITY_UPDATED_BY_ADMIN = 13,
  WEEKLY_PATTERN_UPDATED_BY_ADMIN = 14,
  AVAILABILITY_UPDATED_BY_SELF = 15,
}
